var metadataPhotography = [
        {
            "ID": "000001",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4029-1",
            "CLASSIFICATION": "VIIIA1(1)",
            "DESCRIPTION": "Photo d'Yvan Goll enfant /Photograph of Yvan Goll child",
            "MATERIALS": "Planche contact, reproduction de l'original / Contact print, reproduction",
            "DIMENSIONS": "110 mm X 76 mm",
            "AUTHOR": "H. CULIEL."
        },
        {
            "ID": "000002",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4029-2",
            "CLASSIFICATION": "VIIIA1(2)",
            "DESCRIPTION": "Photo d'Yvan Goll lycéen en 1903 /Photograph of Yvan Goll at the school",
            "MATERIALS": "Reproduction en simili X3",
            "DIMENSIONS": "151 mm X 129 mm",
            "AUTHOR": "L. HERMESTROFF"
        },
        {
            "ID": "000003",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4030",
            "CLASSIFICATION": "VIIIA2",
            "DESCRIPTION": "Photos d'Yvan Goll en blouse russe en 1918 /Photographs of Yvan Goll wearing a Russian blouse in 1918",
            "MATERIALS": "a. 4 réproductions photos d'après positif - noir et blanc, papier glacé + 1 agrandisement exposé; b. 3 réproductions simili extraites d'un livre; c. 2 négatifs"
        },
        {
            "ID": "000004",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4031-1 à 4031-8",
            "CLASSIFICATION": "VIIIA3 (1) à (8)",
            "DESCRIPTION": "Photo d'Yvan Goll entre 1919 et 1928: 1. 1919 (2 photos); 2. 1920; 3.1921; 4. 1921 (2 photos); 5. 1922 à 1924 (2 photos); 6. 1924 en pied (2 ex); 7. 1927 (2 photos); 8. 1928 (4 photos) /Photographs of Yvan Goll between 1919 and 1928",
            "MATERIALS": "Photos noir et blanc, papier glacé / Photos in black and withe, glossy photographic paper",
            "AUTHOR": "E.H. MARTINE"
        },
        {
            "ID": "000005",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4032-1 à 4032-9",
            "CLASSIFICATION": "VIIIA4 (1) à (9)",
            "DESCRIPTION": "Photos d'Yvan Goll , années 1930; 1. 1931; 2. Photos d'après carte d'identité (8 photos); 3 et 4. En Tyrol; 5. 6. 9. portraits; 7. A bicyclette (2 photos); 8. A bicyclette /Yvan Goll’s photographs of the 1930s :  ID cards photographs ; In the Tyrol, portraits, a bicycle",
            "MATERIALS": "Photos en noir et blanc, papier glacé sauf (6) sépia",
            "AUTHOR": "BRASSAI"
        },
        {
            "ID": "000006",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4033-1 à 4033-9",
            "CLASSIFICATION": "VIIIA5 (1) a (9)",
            "DESCRIPTION": "Photos Yvan Goll en Amérique /Photographs of Yvan Goll in America",
            "MATERIALS": "Photos en noir et blanc, papier glacé sauf",
            "AUTHOR": "Allied Press"
        },
        {
            "ID": "000007",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4034",
            "CLASSIFICATION": "VIIIA6 (1) et (2)",
            "DESCRIPTION": "Portrait d'Yvan Goll, février 1949 /Portrait of Yvan Goll from February 1949",
            "MATERIALS": "Portrait de face noir et blanc, papier glacé",
            "DIMENSIONS": "0,173X0,120cm",
            "AUTHOR": "Photomaton AG"
        },
        {
            "ID": "000008",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4035-1 à 4035-3",
            "CLASSIFICATION": "VIIIA7 (1) à (3)",
            "DESCRIPTION": "Photos de Claire Goll enfant: 1. 3. à 3 ans (2 ex); 2. à 12 ans, avec un médaillon, Claire à 3 ans; 3. à 12 ans /Photographs of Claire Goll child (3 years old and 12 years old)",
            "MATERIALS": "1 et 2 photos en noir et blanc, papier glacé; 2 reproduction en simili, nor et blanc, page de livre; 3b original et reproduction de 3a qui est un détail",
            "DIMENSIONS": "1: 11,5X 7,4 cm / 2: 8,2X10,3 cm"
        },
        {
            "ID": "000009",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4036-1 à 4036-4",
            "CLASSIFICATION": "VIIIA8 (1) à (4)",
            "DESCRIPTION": "Photos de Claire Goll: 1. à 16 ans; 2. Au lac de Starnberg à 18 ans en 1909; 3. à Munich en 1909; 4. le 21/12/1911, jour de son mariage avec H Studer /Photographs of Claire Goll at  a young age (16 years old, 18 years old at the Stanberg lake in 1909, in 1909 in Munich and her wedding’s day with H. Studer, December the 21th, 1911)",
            "MATERIALS": "Reproductions noir et blanc, papier glacé",
            "DIMENSIONS": "1: 10,3X5,4 cm / 2: 10,9X8,1 cm / 3: 11,3X10,6 cm / 4: 9X8,3 cm"
        },
        {
            "ID": "000010",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4037-1 à 4037-6",
            "CLASSIFICATION": "VIIIA9 (1) à (6)",
            "DESCRIPTION": "Portraits de Claire GOLL  1918-1927: 1. 1918 à Ascona; 2 et 3. 1921 à Paris; 4. Berlin 1924; 5. Paris 1924; 6. 1927 Robe de Sonia DELAUNAY /Portraits of Claire Goll between 1918 and 1927  in : Ascona, Paris, Berlin, and the Sonia’s Delaunay dress in 1927",
            "MATERIALS": "1: un ex. en papier glacé et 1 ex. papier mat; 2 et 3: papier glacé noir et blanc; 4: Papier glacé noir et blanc et negatif; 5: Papier glacé noir et blanc et negatif; 6: Papier glacé noir et blanc et une reproduction sur line",
            "DIMENSIONS": "1: 16,8X10,9 cm / 2: 22,3X16,6 cm / 3: 22,3X16,6 cm / 4: 24X 17,8 cm / 5: 16,2X12,6 cm / 20,8X 16,2 cm",
            "AUTHOR": "2 et 3: E. H. MARTINE / Riess / 5 et 6 R. Sobol - Paris"
        },
        {
            "ID": "000011",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4038-1 à 4038-9",
            "CLASSIFICATION": "VIIIA10 (1) à (9)",
            "DESCRIPTION": "Photos de Claire Goll 1930-1935: 1. Sur sa terrasse (nu) - Rue Raffet / 2 et 3. Au Château de Moraypré / 4. Luxeuil -Les-Bains / 5. En Italie / 6 et 7. Italie / 8. Sur sa terrasse Rue Raffet, avec ses pigeons / Au Château de Moraypré /Photographs of Claire Goll between 1930 and 1935 : Naked on her roof deck, at the Moraypré Casttle, in Luxeuil-Les-Bains, in Italy, on her roof deck with her doves",
            "MATERIALS": "Noir et blanc papier glacé",
            "DIMENSIONS": "1: 14,2X6,4 cm / 2: 8,2X6,4 cm / 3: 8,1X5,2 cm / 4: 9,1X7 cm / 5: 24,7X15,1 cm / 6: 6,5X37,7 cm / 7: 5X18,3 cm / 8: 17,8X12,2 cm / 9: 12,6X12,3 cm",
            "AUTHOR": "1 à 7 et 9: Yvan Goll / 8: Brassaï"
        },
        {
            "ID": "000012",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4039-1 0 4039-8",
            "CLASSIFICATION": "VIIIA11 (1) à (8) négatifs (5a) (6b)",
            "DESCRIPTION": "Photos de Claire Goll 1939-1946 (USA et Cuba): 1: à l'exposition internationale (a, b,c) / 2: Devant la maison des Goll à Brooklyn / 3: A la Havane - 1940 / 4. Devant le pont de Brooklyn / 5 (a,b,c,) 3 portraits \"Allied Press\" / 6: (a,b) 2 portraits par Carson / 7: Claire dans sa chambre / 8: à la Mac Dowell Colony /Photographs of Claire Goll between 1939 and  1946 in U.S.A and Cuba : International exhibition ; In front of Goll’s house in Brooklyn ; in La Havana, 1940 ; In front of Brooklyn Bridge ; Portraits of « Allied Press » ; Portraits by Carson ; Claire in her bedroom, In the Mac Dowell Colony",
            "MATERIALS": "Noir et blanc. Papier glacé sauf: un ex. de (3) en papier cristal / 5 (a,b,c) en chamois maché / 6 (a,b) reproduction de livre",
            "DIMENSIONS": "1: 6,6X4,2 cm / 2: 7,9X13 cm /3: 24X17,6 cm, 20,2X15 cm, 14,5X11,1 cm / 4: 8,2X12,6 cm / 5a,b,c: 24,1X16,6 cm / 6a: 20X15,9 cm / 6b: 20,2X15,6 cm / 7: 10,9X16,5 cm / 8a,b: 8,9X5,7 cm",
            "AUTHOR": "1,2: Yvan Goll / 3: Lotte Grahm / 5: Allied Press / 6: Robert Carson"
        },
        {
            "ID": "000013",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4040-1 à 4040-4",
            "CLASSIFICATION": "VIIIA12 (1) à (4)",
            "DESCRIPTION": "Photos de Claire Goll de retour en France: 1. Chez Alfred de MILLY / 2. 1955 / 3. à l’hôtel \"Palais d'Orsay\" / 4. en 1965 /Photographs of Claire Goll back in France : At Alfred de Milly’s house ; in 1955 ; At the Palais d’Orsay hotel and photograph from  1965",
            "MATERIALS": "Noir et blanc, papier glacé",
            "DIMENSIONS": "1: 12,5X6,5 cm / 2: 11,6X8,9 cm / 3: 14,8X10,2 cm / 4: 18,6X20,2 cm",
            "AUTHOR": "2. Fritz W. Neugass / 4. Fred Stein"
        },
        {
            "ID": "000014",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4041",
            "CLASSIFICATION": "VIIIA13",
            "DESCRIPTION": "Photo \"Les mains de Claire Goll\"  /Photograph : « Claire Goll’s hands »",
            "MATERIALS": "Noir et blanc, papier mat, représentant le bas du visage et les mains de Claire Goll",
            "DIMENSIONS": "97X126 mm",
            "AUTHOR": "MAN RAY"
        },
        {
            "ID": "000015",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4042-1 à 4042-3",
            "CLASSIFICATION": "VIIIA14 (1) à (3)",
            "DESCRIPTION": "Photos d'Yvan et Claire avant leur exil: 1. Dans leur appartement Rue Raffet / 2. à Berlin en 1927 / 3. Sori /Photographs of Yvan and Claire before their exile : At their appartment in Raffet Street ; In Berlin, 1927 ; Sori",
            "MATERIALS": "Noir et blanc, papier glacé",
            "DIMENSIONS": "1: 9,7X7,4 cm / 2: 16,7X10,9 cm",
            "AUTHOR": "2: L'agrandissement photo Gérard Decaux Sipapress"
        },
        {
            "ID": "000016",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4043",
            "CLASSIFICATION": "VIIIA15 (1) à (3)",
            "DESCRIPTION": "Photos de Claire et Yvan GOLL aux USA: 1. Sur le toit de l'hotel St. George à New York / 3. à Saratoga Springs / 3. à la Mac Dowell Colony /Photographs of Claire et Yvan Goll in U.S.A. : On the roof of the St. George Hotel in New York ; Saratoga Springs ; At the Mac Dowell Colony",
            "MATERIALS": "Noir et blanc, papier glacé et 3c reproduction tiré d'un livre",
            "DIMENSIONS": "1: 10,2X6,8 cm / 2: 15,1X9,8 cm / 3: 5,8X8,9 cm / 4: 12,4X19,5 cm / 5: 12,2X8 cm"
        },
        {
            "ID": "000017",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4044",
            "CLASSIFICATION": "VIIIA16 (1) à (3)",
            "DESCRIPTION": "Photos d'Yvan et Claire au Jardin Botanique de Brooklyn en 1946: 1: Claire et Yvan / 2: Yvan, Claire et Jimmy / 3: Yvan, Claire, Jimmy et un autre homme",
            "MATERIALS": "Papier glacé noir et blanc",
            "DIMENSIONS": "1: 10,3X5,8 cm /2: 6,1X10,6 cm / 3: 6,1X10,6 cm",
            "AUTHOR": "James Kucyniak"
        },
        {
            "ID": "000018",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4045",
            "CLASSIFICATION": "VIIIA17 (1) à (5)",
            "DESCRIPTION": "Photos de la famille de Claire Goll: 1. Le père de Claire / 2. La grand-mère / 3. Claire et son frère / 4. Le frère de Claire vers 6-8 ans / 5. Doralies Studer, fille de Claire /Photographs of the Claire Goll’s Familly ; Claire’s father ; Claire’s Grand-Mother ; Doralies Studer, Claire’s daugther",
            "MATERIALS": "Noir et blanc, papier mat collé sur carton",
            "DIMENSIONS": "1: 11,6X7,8 cm / 2: 19,6X13,2 cm / 3: 24,1X16,1 cm / 4: 22,1X8,2 cm / 5: 11,1 cm diam.",
            "AUTHOR": "Sanson und Co - Munich /Freyrag & Sohn - Nuremberg"
        },
        {
            "ID": "000019",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4046",
            "CLASSIFICATION": "VIIIA18 (1) à (3)",
            "DESCRIPTION": "Photos de la famille d'Yvan Goll: 1: Le père d'Yvan / 2: La mère d'Yvan / 3: La mère d'Yvan, son beau-père et Claire /Photographs of the Yvan Goll’s Familly : Yvan’s father ; Yvan’s mother ; Yvan’s mother, his brother in law and Claire",
            "MATERIALS": "1: Sépia, papier glacé sur carton jaune, reproduction noir et blanc / 2: Noir et blanc, papier mat, négatif de reproduction / 3: Photo sépia, papier glacé",
            "DIMENSIONS": "1: 9,6X5,6 cm / 2: 5,1X5,1 cm / 3: 8X10,1 cm",
            "AUTHOR": "A. Fatalot"
        },
        {
            "ID": "000020",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4047",
            "CLASSIFICATION": "VIIIA19 (1) à (7)",
            "DESCRIPTION": "Photos des appartements des Goll, Rue Raffet à Paris, 16e. N 19: 1. Photo de la façade / 2. Photo de la terrasse / 3. Le pigeonier / 4. Les pigeons .  N.31: 5. La chambre / 6. La cuisine / 7. La salle à manger /Photographs of the Goll’s appartements in Raffet Street, Paris : N. 19 the façade ; the roof deck ; The Dovecote ; The doves ; The bedroom ; the kitchen ; The dining room",
            "MATERIALS": "Noir et blanc, papier glacé",
            "DIMENSIONS": "1: 17,9X12 cm / 2: 17,9X11,7 cm / 3: 10,4X17,8 cm / 4: 18,1X12 cm / 5: 22,5X16,7 cm / 6: 22,5X16,7 cm /7: 16,7X22,5 cm",
            "AUTHOR": "5,6,7 Chevojon"
        },
        {
            "ID": "000021",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4048",
            "CLASSIFICATION": "VIIIA20 (1) à (6)",
            "DESCRIPTION": "Photos: 1. Façade de l'hôtel où habitèrient les Goll en 1919 / 2. Photos du Quai Bourbon où habitèrent les Goll de 1936 à 1937 / 3. Plan partiel de St-Dié et 2 photos de la Rue Concorde où est né Yvan / 4: Photo de la Plaque \"Rue Yvan Goll\" à St-Dié / 5: façsade de la Banque de Lausanne où Yvan travaillait en 1914 / 6: Rue Yvan Goll et détail de la plaque de la Rue /Photographs : The façade of the hotel where the Golls used to live in 1919 ; Photographs of the Bourbon’s wharf, where the Golls have lived between 1936 and 1937 ; Partial Map of Saint-Dié-des-Vosges and two photographs of the Concorde Street, the one where Yvan Goll was born ; Photograph of the Plaque with the street’s name «Yvan Goll »,  in Saint-Dié-des-Vosges ; Façade of the Bank Lausanne where Yvan Goll has worked in 1914 ; Detail of the plaque with the street’s name « Yvan Goll » and street’s photograph",
            "MATERIALS": "1. Carte postale sépia, mat / 2. Noir et blanc, papier glacé / 3a. Photocopie, 3b,c Noir et blanc, papier mat / 4. Noir et blanc, papier mat / 5. Noir et blanc, papier mat / 6. Noir et blanc, papier glacé, négatif",
            "DIMENSIONS": "1: 0,140X0,09 m / 2: 13,4X17,8 cm / 5: 0,14X0,089 m",
            "AUTHOR": "2: Robert Bresson"
        },
        {
            "ID": "000022",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4049",
            "CLASSIFICATION": "VIIIA21 (1) à (5)",
            "DESCRIPTION": "Photos de Groupe des Goll avec des amis artistes: 1. Deux photos d'Yvan et Claire avec Marc Bella et Ida Chagall / 2. Trois photos d'Yvan et Claire avec David et Mary BURLIUK / 3. Yvan et Claire avec Elsa Triolet, Robert Delaunay, Valentine Chodassévich, Maïakowsky / 4. Idem 3 autre clichés / 5. Yvan et Claire avec la romancière Carson McCullers et l'avocat Maurice Speiser /Photographs of The Golls and friends ; Two photographs of Claire and Yvan with Marc Bella and Ida Chagall ; Three photographs of Yvan and Claire with David and Mary Burliuk ; Yvan and Claire with Elsa Triolet, Rober Delaunay, Valentine Chodassévich and Maïakowsky ; Yvan and Claire with the novelist Carson McCullers and the lawyer Maurice Speiser",
            "MATERIALS": "1: Photo en noir et blanc, papier glacé et reproduction noir et blanc pap. Glacé / 2: Photo original noir et blanc, papier mat et reproduction noir et blanc, papier glacé / 3: Photo noir et blanc papier glacé / 4: reproduction noir et blanc simili, papier mat / 5: Reproduction noir et blanc simili, papier mat",
            "DIMENSIONS": "1: 91X143 mm / 2: 122X189 mm / 3: 100X145 mm / 4: 153X129 mm / 153X129 mm"
        },
        {
            "ID": "000023",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4050",
            "CLASSIFICATION": "VIIIA22 (1) à (4)",
            "DESCRIPTION": "1: Photo originale de Julie Kerschensteiner et 1 reproduction / 2: photo de J. Kerschensteiner dans le Jardin de son institut / 3: Photo de la tombe de Julie Kerschensteiner / 4: Photo de J. Kerschensteiner /Original photograph and one reproduction of Julie Kerschensteiner ; Two photographs of Julie Kerschensteiner at the garden of the Institute ; Julie Kerschensteiner’s grave ; J. Kerschensteiner photograph",
            "MATERIALS": "Noir et blanc, papier glacé, et noir et blanc sur carton en papier mat (3)",
            "DIMENSIONS": "1: 99X75 mm / 2: 98X85 mm / 3: 105X86 mm / 4: 80X72 mm"
        },
        {
            "ID": "000024",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4051",
            "CLASSIFICATION": "VIIIA23 (1) à (7)",
            "DESCRIPTION": "Photos d'écrivans, amis de Claire et Yvan Goll: 1. Georg Kaiser et son fils / 2. James Joyce / 3: Rainer Maria Rilke / 4: Arthur Miller et Claire Goll / 5: Henri Miller et Yvan Goll / 6: Claire Goll et Jean-Paul Sartre / 7: Yvan Goll et Victor Von Wendel /Photographs of writers friends of Yvan and Claire Goll : Georg Kaiser and his son ; James Joyce ; Rainer Maria Rilke ; Arthur Miller and Claire Goll ; Henri Miller and Yvan Goll ; Claire Goll and Jean-Paul Sartre ; Yvan Goll and Victor Von Wendel",
            "MATERIALS": "1: Reproduction d'un photo dédicacéz noir et blanc, papiers mat et glacé / 2: Portrait noir et blanc, reproductions papiers mat et glacé / 3: Reproduction noir et blanc, papier mat / 4: Reproduction blanc et noir, papier mat / 5: Reproduction blanc et noir, papier glacé / 6: Original papier glacé et une reproduction / 7: Noir et blanc, papier glacé",
            "DIMENSIONS": "1: 27,7X20,6 cm / 2: 19X14,6 cm / 3: 8,3X5 cm / 4: 24X17,9 cm / 5: 20,3X13,1 cm / 6: 11,8X16,6 cm / 7: 11,7X18 cm",
            "AUTHOR": "1. Riess / 4. Henri DANMAN / 6. M. et E. Photo Service Broadway"
        },
        {
            "ID": "000025",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4052",
            "CLASSIFICATION": "VIIIA24 (1) à (8)",
            "DESCRIPTION": "Photos d'artistes amis d'Yvan et Claire Goll: 1. Claire Goll et CHAGALL / 2. Claire Goll et Jean ARP / 3. Fernand LEGER / 4. Claire Goll et Albert GLEIZES / 5. Jacques VILLON / 6. Claire Goll et UTRILLO / 7. Clare Goll et Antoine CLAVE / 8. Henry MOORE /Photographs of artists  friends of Yvan and Claire Goll : Claire Goll and Chagall ; Claire Goll and Jean Arp ; Fernand Leger ; Claire Goll and Albert Gleizes ; Jacques Villon ; Claire Goll and Utrillo ; Claire Goll and Antoine Clave ; Henri Moore",
            "MATERIALS": "1 à 8: Reproductions des photos orifinales, blanc et noir, papier mat / 1, 3, 5, 7, 8: Détails en papier glacé",
            "DIMENSIONS": "1 à 8: 240X179 mm / 1. et aussi 145X88mm / 2. et aussi 133X130mm / 6. et aussi 238X182 mm / 7. Détail 142X77 mm / 8. et aussi 315X214 mm",
            "AUTHOR": "5: BETTINA-Zurich / 7. Photopress (Courbevoie) / 8: LIDBROOKE"
        },
        {
            "ID": "000026",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4053",
            "CLASSIFICATION": "VIIIA25 (1) à (6)",
            "DESCRIPTION": "1: Portrait du président indien S. RADHAKRISHNAN / 2: Portrait du musicien Gian Carlo MENOTTU / 3: Portrait du Savant atomiste Robert OPPENHEIMER / 4: Photos de Claire Goll avec Gina LOLOBRIGIDA / 5: L'hôtesse de la colonie americaine / 6:Carte postale representant De Gaulle, signée par W. P. HITLER / Portrait of the indian president S. Radhakrishnan ; Portrait of the musician Gian Carlo Menottu ; Portrait of the  theoretical physicist Robert Oppenheimer ; Photographs of Claire Goll and Gina Lolobrigida ; The hostess of the American Colony",
            "MATERIALS": "1 à 5: Reproductions des photos originales noir et blanc, papier mat / 6: Carte postale photo reproduction simili en blanc et noir; au dos signature de William Patrick HITLER, neveu de Adolf HITLER / 4: et aussi reproduction papier glacé",
            "DIMENSIONS": "1 à 5: 240X179 mm / 6: 140X88 mm / 4: Repro 253X205 mm"
        },
        {
            "ID": "000027",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4054",
            "CLASSIFICATION": "VIIIA26 (1) et (2)",
            "DESCRIPTION": "2 Pochettes de negatifs films en noir et blanc /Two pouches with negative films in black and white",
            "MATERIALS": "1: 12 poses 6X6 / 2: 12 poses 6X6 and 3 poses 6X6"
        },
        {
            "ID": "000028",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4055",
            "CLASSIFICATION": "VIIIA27",
            "DESCRIPTION": "Photos reproductions d'un dessin: \"Claire Goll par Albert GLEIZES\" /Photo reproductions of a drawing",
            "MATERIALS": "Photos  en noir et blanc, papier glacé. Dessin esquisse au crayon gras ou fusain",
            "DIMENSIONS": "1 et 3: 297X211 mm / 2: 258X204 mm",
            "AUTHOR": "Esquisse: Albert GLEIZES"
        },
        {
            "ID": "000029",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4056",
            "CLASSIFICATION": "VIIIA28",
            "DESCRIPTION": "Reproduction photo d'un tableau: \"Claire Goll\" par Albert GLEIZES /Photo reproduction of a painting : « Claire Goll » by Albert Gleizes",
            "MATERIALS": "Photo en blanc et noir, papier glacé / tableau: huile sur toile",
            "DIMENSIONS": "photo: 242X182 mm",
            "AUTHOR": "Tableau: Albert GLEIZES"
        },
        {
            "ID": "000030",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4057",
            "CLASSIFICATION": "VIIIA29",
            "DESCRIPTION": "Reproductions photos d'un dessin: \"Yvan GOLL\" par Albert GLEIZES /Photo reproductions of a drawing : « Yvan Goll » by Albert Gleizes",
            "MATERIALS": "Photo: noir et blanc, papier glacé / original: dessin au crayon gras ou fusain",
            "DIMENSIONS": "1: 258X204 mm / 2: 2397X211 mm",
            "AUTHOR": "Original: Albert GLEIZES"
        },
        {
            "ID": "000031",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4058",
            "CLASSIFICATION": "VIIIA30",
            "DESCRIPTION": "3 reproductions d'un portrait de Claire Goll par Robert DELAUNAY / 3reproductions of  Claire Goll’s portrait by Robert Delaunay",
            "MATERIALS": "Reproductions: photos en noir et blanc, papier glacé; simili noir et blanc, papier semi mat, extrait de : \"C. Goll\" Poètes d'aujourd'hui.",
            "DIMENSIONS": "216X168 mm / 153X129 mm / 239X183 mm, papier collé au bas: 22X157 mm",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000032",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4059",
            "CLASSIFICATION": "VIIIA31",
            "DESCRIPTION": "5 reproductions photo d'un portrait d'Yvan Goll par Robert DELAUNAY, une reproduction extrait d'un livre /5 photo reproductions of  Yvan Goll’s portrait by Robert Delaunay",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: dessin au crayon",
            "DIMENSIONS": "1. 0,178X0,123 m / 2. 0,130X0,86 m / 3. 0,118X0,88 m / 4. 0,114X0,86 m / 5. 0,209X0,132 m",
            "AUTHOR": "Dessin original: Robert DELAUNAY"
        },
        {
            "ID": "000033",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4060",
            "CLASSIFICATION": "VIIIA32 (Négatif voir A26)",
            "DESCRIPTION": "Reproduction photo d'un autoportrait de Robert DELAUNAY /Photo reproduction of a Robert Delaunay’s portrait",
            "MATERIALS": "Photo noir et blanc, papier mat / original: Huil sur toile",
            "DIMENSIONS": "Photo: 239X179 mm / original: 550X460 mm",
            "AUTHOR": "Original: Robert DELAUNAY / Reproduction réalisée d'après une photo de Marc VAUX (Paris)"
        },
        {
            "ID": "000034",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4061",
            "CLASSIFICATION": "VIIIA33 (1) et (2) (négatifs)",
            "DESCRIPTION": "1: 9 reproductions photos du dessin de CHAGALL \"Yvan Goll profil droit\" / 2: négatif  plan film /N. 1 : Nine photo reproductions of Chagall’s drawing : « Yvan Goll right profile » / N. 2 : Negative film",
            "MATERIALS": "1: Photos noir et blanc, papier glacé (6 ex.), 3 reproductions sur line / 2: Négatif plan film / Original; dessin à l'encre",
            "AUTHOR": "Original: Dessin CHAGALL"
        },
        {
            "ID": "000035",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4062",
            "CLASSIFICATION": "VIIIA34 (négatifs)",
            "DESCRIPTION": "8 reproductions photos d'un dessin-collage \"Claire et Yvan Goll\" par CHAGALL /Eight photo reproductions of a drawing – collage, « Claire and Yvan », by Chagall",
            "MATERIALS": "5 reproductions photos noir et blanc, papier glacé dont 1 collée sur papier calque / 3 reproductions extraites de lines",
            "AUTHOR": "Original: études des profils de Claire et Yvan au crayon, juxtaposition par collage"
        },
        {
            "ID": "000036",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4063",
            "CLASSIFICATION": "VIIIA35 (1) et (2) négatifs",
            "DESCRIPTION": "2 reproductions, une photo et un négatif. Dessin de Claire par Jacques Audiberti / Two photo reproductions (photograph and negative) of a drawing of Claire by Jacques Audiberti",
            "MATERIALS": "1: Photo en noir et blanc, papier glacé / 2: négatif plan film / Original: dessin au crayon ou à la plume, profil de Claire avec flammes",
            "AUTHOR": "Original: Jacques AUDIBERTI"
        },
        {
            "ID": "000037",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4064",
            "CLASSIFICATION": "VIIIA36",
            "DESCRIPTION": "Reproduction photo: Portrait caricaturé d'Yvan par Jacques AUDIBERTI /Photo reproduction of a cartoon portrait of Yvan by Jacques Audiberti",
            "MATERIALS": "Photo en blanc et noir, papier glacé / Original: dessin au crayon",
            "DIMENSIONS": "Photo: 152X120 mm",
            "AUTHOR": "Dessin: Jacques AUDIBERTI"
        },
        {
            "ID": "000038",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4065",
            "CLASSIFICATION": "VIIIA37",
            "DESCRIPTION": "Photocopie d'un dessin d'Yvan GOLL par GATTORNO /Photocopy of a drawing of Yvan Goll by Gattorno",
            "MATERIALS": "Photocopie en noir et blanc / Original: Extrait d'une page du journal LA VOIX DE France du 1er janvier 1942, \"Page de la Poèsie\"",
            "DIMENSIONS": "139X210 mm",
            "AUTHOR": "Dessin: GATTORNO"
        },
        {
            "ID": "000039",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4066",
            "CLASSIFICATION": "VIIIA38",
            "DESCRIPTION": "2 reproductions photos d'un portrait d'Yvan Goll par R. R. JUNGHANS /2 photo reproductions of a portrait of Yvan Goll by R. R. Junghans",
            "MATERIALS": "Photo en noir et blanc, papier glacé",
            "DIMENSIONS": "0,184X0,117 m",
            "AUTHOR": "Original: JUNGHANS"
        },
        {
            "ID": "000040",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4067",
            "CLASSIFICATION": "VIIIA39",
            "DESCRIPTION": "Reproduction photo d'un tableau: \"Yvan en Blouse russe\" (3 ex.) /Photo reproduction of a painting : « Yvan Goll in a Russian blouse » (in triplicate)",
            "MATERIALS": "Photos noir et blanc, papier glacé / original huile sur toile"
        },
        {
            "ID": "000041",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4068",
            "CLASSIFICATION": "VIIIA40",
            "DESCRIPTION": "Reproduction photos d'un dessin à la plume \"Claire\" par KOKOSCHKA (3 ex.) /Photo reproduction of a pen drawing : « Claire », by Kokoschka (in triplicate)",
            "MATERIALS": "Photo noir et blanc, papier glacé / original: dessin à la plume, à l'encre",
            "AUTHOR": "Original: KOKOSCHKA"
        },
        {
            "ID": "000042",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4109",
            "CLASSIFICATION": "VIIIA41 (1) et (2)",
            "DESCRIPTION": "1: Portrait de Claire par Kokoschka (photo) / 2: négatif /N. 1 : Portrait of Claire Goll by Kokoschka (photograph) / N. 2 : Negative",
            "MATERIALS": "Photo noir et blanc, papier glacé /  négatif plan-film noir et blanc / original: dessin à la plume, encre noire",
            "DIMENSIONS": "1: 0,158X0,123 m / 2: 0,120X0,95 m",
            "AUTHOR": "Original: Oscar KOKOSCHKA"
        },
        {
            "ID": "000043",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4110",
            "CLASSIFICATION": "VIIIA42",
            "DESCRIPTION": "Reproduction photos d'un dessin \"Portrait de Claire\" (3ex.) /Photo reproduction of a drawing : « Portrait of Claire » (in triplicate)",
            "MATERIALS": "Photos en noir et blanc, papier glacé / Original: dessin au crayon et fusain sur papier",
            "AUTHOR": "Original: G. ANNENKOV"
        },
        {
            "ID": "000044",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4111",
            "CLASSIFICATION": "VIIIA43 (1) et (2)  négatif",
            "DESCRIPTION": "Reproduction photos d'un dessin \"Portrait de Claire\" (4 ex.) / Négatif plan film (1 exp.) /Photo reproduction of a drawing : « Portrait of Claire » / Negative film",
            "MATERIALS": "Photos noir et blanc, papier glacé (4 ex.) / négatif plan-film / Original: Dessin au trait, à l'encre noire, composition abstraite",
            "AUTHOR": "Original: Fernand LEGER"
        },
        {
            "ID": "000045",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4112",
            "CLASSIFICATION": "VIIIA44 (1) et (2) négatif",
            "DESCRIPTION": "1. Reproductions photos d'un dessin \"Portrait de Claire\" (2 ex.) / 2. Négatif /N. 1 : Photo reproduction of a drawing «Portrait of Claire » (in duplicate) / N. 2 Negative",
            "MATERIALS": "1. Photos noir et blanc, papier glacé / 2. Négatif plan film / Original: dessin à l'encre noir et gouache blanche",
            "AUTHOR": "Original: Joseph SIMA"
        },
        {
            "ID": "000046",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4113",
            "CLASSIFICATION": "VIIIA45 (1) à (4) négatif",
            "DESCRIPTION": "Reproductions photos: Buste de Claire Goll /Photo reproductions : Bust of Claire Goll",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: buste en terre cuite",
            "AUTHOR": "Original: Llly RONA"
        },
        {
            "ID": "000047",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4114",
            "CLASSIFICATION": "VIIIA46",
            "DESCRIPTION": "Reproductions phots d'un dessin \"Caricatures de Colette, A. Gide, Le Corbusier, Claire et Yvan Goll\" /Photo reproductions of a drawing «Cartoon of Colette, A. Gide, Le Corbusier, Claire and Yvan Goll»",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: dessin à l'encre noire, sur papier",
            "DIMENSIONS": "0,247X0,180 m",
            "AUTHOR": "Original: Kresler Adolf HOFFMEISTER"
        },
        {
            "ID": "000048",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4115",
            "CLASSIFICATION": "VIIIA47 (1) à (3)",
            "DESCRIPTION": "Reproductions photos d'un dessin \"Claire et Yvan Goll\" de FOUJITA (4 ex.) / (47-2) Claire séule après découpé (2 ex.) /Photo reproductions or a drawing «Claire and Yvan Goll » by Foujita / (47-2) Claire alone (after cutting) in duplicate",
            "MATERIALS": "Photos noir et blanc , papier glacé / Original: dessin à l'encre noir sur papier",
            "DIMENSIONS": "0,40X0,303 m",
            "AUTHOR": "Original: Tsuguhan FOUJITA"
        },
        {
            "ID": "000049",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4116",
            "CLASSIFICATION": "VIIIA48",
            "DESCRIPTION": "Cartes postales (2 ex.)  \"La fenétre du poète Claire Goll\" /Postcards (in duplicate) « The window of the poet Claire Goll »",
            "MATERIALS": "Tirage offset sans trame, papier  mat, couleur sépia / Original: gravure",
            "DIMENSIONS": "0,140X0,100 m",
            "AUTHOR": "Mady de la GIRANDIERE"
        },
        {
            "ID": "000050",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4117",
            "CLASSIFICATION": "VIIIA49 (1) et (2)",
            "DESCRIPTION": "Tombeau d'Yvan Goll au cimentière du Père Lachaise - Paris: 1. Cartes postales (2 ex.) / 2. Photos (2 ex.) /Yvan Goll’s grave at the Père Lachaise Cemetery, Paris. Postcards (in duplicate) and Two photographs",
            "MATERIALS": "Cartes: tirage offset sant trame, papier bristol mat, couleur sépia / Original: plume, sépia / Photos noir et blanc, papier glacé",
            "DIMENSIONS": "1: 14X10,4 cm / 2: 20,8X17,6 cm",
            "AUTHOR": "Original: F. GILOT"
        },
        {
            "ID": "000051",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4118",
            "CLASSIFICATION": "VIIIA50",
            "DESCRIPTION": "Reproductions photos d'un collage \"La tombe d'Yvan au Père Lachaise\" (2 ex.) /Photo reproductions of a collage « Yvan Goll’s grave at Père Lachaise » (in duplicate",
            "MATERIALS": "Photos noir et blanc / Original: Collage",
            "AUTHOR": "Original: Antoni CLAVE"
        },
        {
            "ID": "000052",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4119",
            "CLASSIFICATION": "VIIIA51",
            "DESCRIPTION": "Reproductions photos d'un dessin \"Les chapitres entremélés du roman\" (3 ex.) /Photo reproductions of a drawing « The novel’s mixed chapters » (in triplicate)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Original Ilya EHRENBURG"
        },
        {
            "ID": "000053",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4120",
            "CLASSIFICATION": "VIIIA52 (1) à (6)",
            "DESCRIPTION": "Reproduction des 4 illustrations de: \"Elégie d'Ihpétonga /Reproductions of the four illustrations from  « The Elegy of Ihpetonga »",
            "MATERIALS": "1: Photo noir et blanc, papier glacé (2 ex.) / 2: Illustration extraite d'un livre / 3,4,5: Photos noir et blanc, papier glacé / 6: Page de titre \"Elégie d'Ihpetonga\" / Original: Lithographie",
            "AUTHOR": "Original: Pablo PICASSO"
        },
        {
            "ID": "000054",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4121",
            "CLASSIFICATION": "VIIIA53",
            "DESCRIPTION": "Reproduction photo d'une illustration pour \"Jean sans terre\" d'Yvan Goll /Photo reproduction of an illustration for « John without Land » by Yvan Goll",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: encre noire, gravure",
            "DIMENSIONS": "180X127 mm",
            "AUTHOR": "Original: Kurt SELIGMANN"
        },
        {
            "ID": "000055",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4122",
            "CLASSIFICATION": "VIIIA54",
            "DESCRIPTION": "Négatif d'une illustration pour \"Mathusalem\" d'Yvan Goll /Negative of an illustration for «MAthusalem » by Yvan Goll",
            "MATERIALS": "Négatif plan film, noir et blanc",
            "DIMENSIONS": "120X95 mm",
            "AUTHOR": "Original: George GROSZ"
        },
        {
            "ID": "000056",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4123",
            "CLASSIFICATION": "VIIIA55 (1) à (6) négatifs (3) et (4)",
            "DESCRIPTION": "Décors: \"Les Immortels\" d'Yvan Goll - \"L'Assurance contre le suicide\" /Photographs of the scenery for « The immortals » by Yvan Goll - « The insurance for the suicide »",
            "MATERIALS": "1,2: Photos noir et blanc, papier glacé / 3,4: négatif plan film / 5,6: phots collages ayant servi pour les clichés 3 et 4",
            "AUTHOR": "Original: Viala AKAKIA"
        },
        {
            "ID": "000057",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4124",
            "CLASSIFICATION": "VIIIA56 (Négatif voir A26)",
            "DESCRIPTION": "Reproduction photo d'un autoportrait de COLETTE (2ex.) /Photo reproduction of a Colette’s self-portrait (in duplicate)",
            "MATERIALS": "Photo noir et blanc, papiers mat et glacé / Original: dessin au fusain",
            "DIMENSIONS": "0,239X0,178 m / 0,240X,0176 m",
            "AUTHOR": "Original: COLETTE"
        },
        {
            "ID": "000058",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4125",
            "CLASSIFICATION": "VIIIA57",
            "DESCRIPTION": "Photo reproduction d'un autoportrait d'Yvan Goll /Photo reproduction of an Yvan Goll’s self-portrait",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "183X131 mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000059",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4126",
            "CLASSIFICATION": "VIIIA58",
            "DESCRIPTION": "Reproduction photo d'un autoportrait d'Yvan Goll /Photo reproduction of an Yvan Goll’s self-portrait",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: dessin au crayon",
            "DIMENSIONS": "180X129 mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000060",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4127",
            "CLASSIFICATION": "VIIIA59",
            "DESCRIPTION": "Reproduction photo d'un autoportrait d'Yvan Goll /Photo reproduction of an Yvan Goll’s self-portrait",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original dessin au cayon et à l'encre sur papier",
            "DIMENSIONS": "204X150mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000061",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4128",
            "CLASSIFICATION": "VIIIA60",
            "DESCRIPTION": "Reproduction photo d'un autoportrait d'Yvan Goll /Photo reproduction of an Yvan Goll’s self-portrait",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: dessin à l'encre sur papier",
            "DIMENSIONS": "203X150 mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000062",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4129",
            "CLASSIFICATION": "VIIIA61",
            "DESCRIPTION": "Photo reproduction d'un autoportrait d'Yvan Goll /Photo reproduction of an Yvan Goll’s self-portrait",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: dessin à l'encre sur papier",
            "DIMENSIONS": "207X147 mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000063",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4130",
            "CLASSIFICATION": "VIIIA62",
            "DESCRIPTION": "1. Reproductions photos d'une empreinte de la main d'Yvan (3 ex.) / 2. Négatif / 3. Même cliché tramé /Photo reproduction of the Yvan’s handprint (in triplicate) / Negative / the same shot",
            "MATERIALS": "1. Photo noir et blanc, papier glacé / 2. Négatif / 3. Tramé",
            "DIMENSIONS": "1. 0,240X0,182 mm / 2. 0,181X0,130 mm"
        },
        {
            "ID": "000064",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4131",
            "CLASSIFICATION": "VIIIA63",
            "DESCRIPTION": "Reproduction photo d'un dessin d'Yvan Goll \"An Liliane\"  (2 ex) /Photo reproduction of a drawing « An Liliane », by Yvan Goll (In duplicate)",
            "MATERIALS": "Photocophie en noir et blanc, papier mat",
            "DIMENSIONS": "300X398 mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000065",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4132",
            "CLASSIFICATION": "VIIIA64 (1) et (2)",
            "DESCRIPTION": "Photocopies et un négatif d'un dessin \"Der urvogel\" d'Yvan Goll /Photocopies and a negative of a drawing « Der urvogel » by Yvan Goll",
            "MATERIALS": "1. Photocopie noir et blanc, papier mat / 2. Négatif film / Original: dessin à l'encre sur papier",
            "DIMENSIONS": "Photocopie: 124X74 mm et 129X72 mm / Négatif: 37X25 mm",
            "AUTHOR": "Original: Yvan Goll"
        },
        {
            "ID": "000066",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4133",
            "CLASSIFICATION": "VIIIA65",
            "DESCRIPTION": "(1a) Illustration d'Antoni CLAVE pour \"Les larmes pétrifiées\" de Claire Goll (3 ex.) (2a et 2b illustrations pour l'édition allemande (3 ex.) /",
            "MATERIALS": "Illustration procédé de reproduction au point trait noir et blanc sur papier chiffon / Original: Dessin",
            "DIMENSIONS": "0,178X0,108 m / VIIIA65 (4a) 10,5X14,5 / 2b 11,5X17",
            "AUTHOR": "Original: Antoni CLAVE"
        },
        {
            "ID": "000067",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4134",
            "CLASSIFICATION": "VIIIA66",
            "DESCRIPTION": "La maison de Hans Christian ANDERSEN, Vues luteriennes",
            "MATERIALS": "2 cartes postales noir et blanc, papier glacé",
            "DIMENSIONS": "103X146 mm"
        },
        {
            "ID": "000068",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4135",
            "CLASSIFICATION": "VIIIA67",
            "DESCRIPTION": "Photo de Eric SELLIN",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "93X66 mm"
        },
        {
            "ID": "000069",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4146",
            "CLASSIFICATION": "VIIIA68",
            "DESCRIPTION": "2 cartes postales de Sasia EHRLICH (1) Paris, Eglise Saint Germain des Prés / (2) Alger, BAB-EL-OURD et N.D. d'Afrique",
            "MATERIALS": "Cartes postales noir et blanc, papier glacé",
            "DIMENSIONS": "90X140 mm"
        },
        {
            "ID": "000070",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4137",
            "CLASSIFICATION": "VIIIA69",
            "DESCRIPTION": "Carte postale de la Havane \"Paysage cubain\"",
            "MATERIALS": "Carte postale en couleurs",
            "DIMENSIONS": "137X87 mm"
        },
        {
            "ID": "000071",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4138",
            "CLASSIFICATION": "VIIIA70",
            "DESCRIPTION": "Photos d'écrivains et d'artistes amis de Clare et Yvan Goll: 1: Anna de Noailles - Sergei EINSENSTEIN / 2: Ossip ZADKIN - Maurice de VLAMINCK / 3: Henry MILLER - Salvador DALI / 4: Tristan TZARA- Moïse KISLING / 5: Marc CHAGALL - Alexander CALDER / 6: Serge LIFAR - Olga SPESSIOTZE / VA - Marc, Bella et Ida CHAGALL",
            "MATERIALS": "Photos noir et blanc, pages extraites d'un recueil. Les photos sont accompagnées de notices en allemand",
            "DIMENSIONS": "0,304X0,257 m",
            "AUTHOR": "Originaux: 3: Miller et Doli, BRASSAÏ / 6: Les CHAGALL par André KERTESZ"
        },
        {
            "ID": "000072",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4139",
            "CLASSIFICATION": "VIIIA71 (1) (2) (3a, 3b) (4)",
            "DESCRIPTION": "(1) Etude des mains de Claire Goll par Marc CHAGALL, buste et mains croisées; Claire profil droit et gauche / (2) Détail des mains / (3) Dessin mains croisées et buste remplacé par portrait d'Yvan (après montage)/ (3a) Collage portrait de Claire profil droit et de la signature de CHAGALL / (3b) Tirage de 3a / (4) Portrait d'Yvan et Claire profil gauche",
            "MATERIALS": "Photos noir et blanc, papier glacé / 3a. Collage",
            "DIMENSIONS": "1: 198X157 mm / 2: 121X100 mm / 3a: 187X143 mm / 3b: 248X192 mm / 247X187 mm",
            "AUTHOR": "Dessins originaux: Marc CHAGALL"
        },
        {
            "ID": "000073",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4140",
            "CLASSIFICATION": "VIIIA72",
            "DESCRIPTION": "Doralies, la fille de Claire Goll, reproduction",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "109X66 mm"
        },
        {
            "ID": "000074",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4141",
            "CLASSIFICATION": "VIIIA73",
            "DESCRIPTION": "Claire et Justus - Reproduction",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "241X177 mm"
        },
        {
            "ID": "000075",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4142",
            "CLASSIFICATION": "VIIIA74",
            "DESCRIPTION": "Reproduction d'un cliché \"Le chat des Goll\"",
            "MATERIALS": "Détail de cliché, photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,137X0,78 m"
        },
        {
            "ID": "000076",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4143",
            "CLASSIFICATION": "VIIIA75",
            "DESCRIPTION": "Reproduction d'une photo fenètre de la salle de bains de Claire Goll, Rue Raffet",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,173X0,113 m"
        },
        {
            "ID": "000077",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4144",
            "CLASSIFICATION": "VIIIA76",
            "DESCRIPTION": "Reproduction d'une photo \"Pigeoniers des Goll, Rue Raffet (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "0,177X0,107 m"
        },
        {
            "ID": "000078",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4145",
            "CLASSIFICATION": "VIIIA77",
            "DESCRIPTION": "Reproduction d'une photo \"Le Pont Marie",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,199X0,148 m"
        },
        {
            "ID": "000079",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4146",
            "CLASSIFICATION": "VIIIA78",
            "DESCRIPTION": "Reproduction d'une photo \"Claire devant l'hôtel à Bellagio\"",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,198X0,16 m"
        },
        {
            "ID": "000080",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4147",
            "CLASSIFICATION": "VIIIA79",
            "DESCRIPTION": "The Brooklyn Bridge",
            "MATERIALS": "Reproduction , photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,195X0,118 m"
        },
        {
            "ID": "000081",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4148",
            "CLASSIFICATION": "VIIIA80",
            "DESCRIPTION": "Le Palais Universitaire de Strasbourg",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,127X0,177 m"
        },
        {
            "ID": "000082",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4149",
            "CLASSIFICATION": "VIIIA81",
            "DESCRIPTION": "Claire Goll sur les escaliers d'une église",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "0,175X0,232 m"
        },
        {
            "ID": "000083",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4150",
            "CLASSIFICATION": "VIIIA82",
            "DESCRIPTION": "Yvan Goll et Victor Wendel",
            "MATERIALS": "Petite photo noir et blanc, papier glacé, collé sur carton",
            "DIMENSIONS": "38X56 mm, carton 83X90 mm environ"
        },
        {
            "ID": "000084",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4151",
            "CLASSIFICATION": "VIIIA83",
            "DESCRIPTION": "Yvan Goll étudiant (4 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "0,091X0,065 m / 0,172X0,120 m / 0,174X0,118 m / 0,175X0,119 m"
        },
        {
            "ID": "000085",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4152",
            "CLASSIFICATION": "VIIIA84",
            "DESCRIPTION": "Yvan dans sa chambre, Rue Jasmin (4 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "0,125X0,111 / 0,171X0,117 m / 0,244X0,161 m / 0,229X0,160 m"
        },
        {
            "ID": "000086",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4153",
            "CLASSIFICATION": "VIIIA85 (1) à (3)",
            "DESCRIPTION": "Photos d'Yvan Goll au bord d'une cascade (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "0,230X0,159 m / 0,152X0,120 m / 0,194X0,128 m / 0,198X0,110 m"
        },
        {
            "ID": "000087",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4154",
            "CLASSIFICATION": "VIIIA86 (1) à (4)",
            "DESCRIPTION": "4 portraits d'Yvan Goll",
            "MATERIALS": "1: Reproduction d'une photo d'extérieur. Noir et blanc, papier glacé / 2: Yvan lisant \"Poèmes d'amour\" de Claire et Yvan Goll. Noir et blanc, papier glacé/ 3: Photo d'identité. Noir et blanc, papier glacé / 4: Photomaton? Papier cristal",
            "DIMENSIONS": "(1) 123X115 mm / (2)190X151 mm / (3) 64X51 mm / (3) 64X51 mm / (4) 54X45 mm"
        },
        {
            "ID": "000088",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4155",
            "CLASSIFICATION": "VIIIA87",
            "DESCRIPTION": "Claire Goll à sa fenètre (3 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "0,304X0,20 m / 0,274X0,186 m / 0,239X0,162 m"
        },
        {
            "ID": "000089",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4156",
            "CLASSIFICATION": "VIIIA88",
            "DESCRIPTION": "Claire à 17 ans (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "0,179X0,121 m"
        },
        {
            "ID": "000090",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4157",
            "CLASSIFICATION": "VIIIA89 (1) à (4)",
            "DESCRIPTION": "Portraits de Claire Goll, (1) la représente en pied, (2) 3 ex.",
            "MATERIALS": "1,2,4 papier glacé, photos en noir et blanc / 3 tramé",
            "DIMENSIONS": "1: 20,1X15,1 cm / 2: 24,2X17 cm / 3: 11,5X8,5 cm / 24,2X17,8 cm",
            "AUTHOR": "1: Yvan Goll / 2: Brassaï"
        },
        {
            "ID": "000091",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4158",
            "CLASSIFICATION": "VIIIA90 (1) à (3)",
            "DESCRIPTION": "Portrait de Claire Goll en USA",
            "MATERIALS": "3 photos noir et blanc, papier glacé",
            "DIMENSIONS": "1: 253X149 mm / 196X125 mm / 242X178 mm",
            "AUTHOR": "Yvan Goll"
        },
        {
            "ID": "000092",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4159",
            "CLASSIFICATION": "VIIIA91 (1) à (3)",
            "DESCRIPTION": "Portraits de vieillese de Claire Goll",
            "MATERIALS": "Photos noir et blanc, papier glacé (3) d'après un article de journal",
            "DIMENSIONS": "1: 0,163X0,243 m / 2: 0,300X0,202 m / 3: 0,127X0,181 m",
            "AUTHOR": "1: Andrea Bixlay - Smith / 2: Gérard Decaux / 3: Cliché Schmetzer"
        },
        {
            "ID": "000093",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4160",
            "CLASSIFICATION": "VIIIA92 (1) à (4)",
            "DESCRIPTION": "Photos d'identité de Claire Goll (1) 2 ex. / (2) 2 ex. / (3) 3 ex.",
            "MATERIALS": "1 à 3 photos en noir et blanc et papier mat et glacé / 4. Negatif de (3)",
            "DIMENSIONS": "1: 5,2X4,8 cm / 2: 5,3X4,6 cm / 3: 5,6X4,8 cm"
        },
        {
            "ID": "000094",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4161",
            "CLASSIFICATION": "VIIIA93 (1) à (4)",
            "DESCRIPTION": "Yvan et Claire Goll",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "1: 12X8,9 cm / 2: 24X18 cm / 3: 24X18 cm / 24,2X15,9 cm"
        },
        {
            "ID": "000095",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4162",
            "CLASSIFICATION": "VIIIA94 (1) à (3)",
            "DESCRIPTION": "Portraits d'Yvan Goll par des artistes",
            "MATERIALS": "Photos noir et blanc, papier glacé, originaux: dessins",
            "DIMENSIONS": "1: 0,120X0,067 m / 2: 0,178X0,127 m / 3: 0,254X208 m",
            "AUTHOR": "Originaux: 1: Yvan Goll / 2: CHAGALL / 3: Zadkine"
        },
        {
            "ID": "000096",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4163",
            "CLASSIFICATION": "VIIIA95 (1) à (5) / négatif 2,3,4,5",
            "DESCRIPTION": "Portraits de Claire Goll par des artistes. (4) 4 ex.  (5) 2 ex.",
            "MATERIALS": "Photos noir et blanc, papier glacé, originaux: dessins",
            "AUTHOR": "1: Yvan Goll / 3: Andiberti / 4: Mario Stall / 5: Françoise Gilot"
        },
        {
            "ID": "000097",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4164",
            "CLASSIFICATION": "VIIIA96 (1) à (3) négatif 1,3",
            "DESCRIPTION": "Portraits de Claire Goll: 1 et 2 par Jawlensky (2 ex.) / 3 par Mela Muter (2 ex.)",
            "MATERIALS": "1, 3: Photos noir et blanc, papier glacé / 2: Extrait d'un livre, tramé / Originaux: 1 et 2 dessins, 3 peinture",
            "AUTHOR": "Originaux: 1 et 2: Jawlensky / 3: Mela Muter"
        },
        {
            "ID": "000098",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4165",
            "CLASSIFICATION": "VIIIA97 (1) à (6), négatif 1,3,4,6",
            "DESCRIPTION": "Portraits de Claire et Yvan Goll par Marc CHAGALL: (1) 3 ex. plus 1 ex. frand format de VIIIA97(5)",
            "MATERIALS": "Photos noir et blanc, papier glacé sauf (2) tramé, extrait d'un livre / Originaux: dessins et (6) négartif de (5)",
            "DIMENSIONS": "5: Grand format 0,399 mX 0,305 m",
            "AUTHOR": "Originaux: Marc CHAGALL"
        },
        {
            "ID": "000099",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4166",
            "CLASSIFICATION": "VIIIA98",
            "DESCRIPTION": "Photo d'Yvan Goll en Suisse (2 ex.)",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000100",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4167",
            "CLASSIFICATION": "VIIIA99",
            "DESCRIPTION": "Photo d'Yvan Goll",
            "MATERIALS": "Photo noir et blanc, papier mat"
        },
        {
            "ID": "000101",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4168",
            "CLASSIFICATION": "VIIIA100 (1) à (3)",
            "DESCRIPTION": "56 photos de Claire Goll (en Studio) Fond Claire: (1) Clichés 1 à 20 / (2) clichés 21 à 40 / (3) Clichés 41 à 56",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Dan Jugnet, Maywald (Paris)"
        },
        {
            "ID": "000102",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4169",
            "CLASSIFICATION": "VIIIA101",
            "DESCRIPTION": "20 photos de Claire Goll (en studio) fond noir (N. 57à 76) / (Suite de VIIIA100)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Dan Jugnet, Maywald (Paris)"
        },
        {
            "ID": "000103",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4170",
            "CLASSIFICATION": "VIIIA102 (1) à (5)",
            "DESCRIPTION": "Photos de Claire Goll:1: (2 ex.) cliché N. 32 de VIIIA100(2) / 2: (2ex.) Cliché N. 13 de VIIIA100(1)/ 3: N.14 de vIIIA100(1) / 4: N. 55 de VIIIA100(3)/ 5: N.42 de VIIIA100(3)",
            "MATERIALS": "1: Papier glacé / 2: papiers mat et glacé / 3,4,5: Papier mat",
            "DIMENSIONS": "1: 27,6X22 cm et 30,5X24,2 cm / 2: 24,3X28,6 cm / 3,4,5: 29,9X24 cm",
            "AUTHOR": "Dan Jugnet, Maywald (Paris)"
        },
        {
            "ID": "000104",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4171",
            "CLASSIFICATION": "VIIIA103",
            "DESCRIPTION": "19 photos de Claire Goll (en extérieur) N. 77 à 94 avec un 81 bis",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Dan Jugnet, Maywald (Paris)"
        },
        {
            "ID": "000105",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4172",
            "CLASSIFICATION": "VIIIA104 (1) et (2)",
            "DESCRIPTION": "Photos de Claire Goll: 1. N. 93 de VIIIA103 / 2. N. 88 de VIIIA103",
            "MATERIALS": "Noir et blanc, papier mat / noir et blanc, papier glacé (2 ex.) papier mat (1 ex.)",
            "AUTHOR": "Dan Jugnet, Maywald (Paris)"
        },
        {
            "ID": "000106",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4173",
            "CLASSIFICATION": "VIIA105 (1) et (2)",
            "DESCRIPTION": "2 photos de Claire Goll",
            "MATERIALS": "Noir et blanc, papier glacé",
            "DIMENSIONS": "",
            "AUTHOR": "1: Fred Stein (New York) / 2: Abrisa Tüllmann"
        },
        {
            "ID": "000107",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4174",
            "CLASSIFICATION": "VIIIA106 (1) et (2)",
            "DESCRIPTION": "Photos d'André MALRAUX: (1) dédicacée / (2) copie de la photo dédicacée",
            "MATERIALS": "Photo noir et blanc, papier glacé. Copies",
            "DIMENSIONS": "22,4X15,9 cm",
            "AUTHOR": "Gisèle Freund (Reproduction)"
        },
        {
            "ID": "000108",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4175",
            "CLASSIFICATION": "VIIIA107",
            "DESCRIPTION": "Yvan Goll et Dos Passos",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000109",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4176",
            "CLASSIFICATION": "VIIIA108 (1) et (2)",
            "DESCRIPTION": "Claire Goll filmée tandis qu'elle fait son marché",
            "MATERIALS": "Photos noir et blanc: 1. Papier mat/ 2. Papier glacé"
        },
        {
            "ID": "000110",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4177",
            "CLASSIFICATION": "VIIIA109",
            "DESCRIPTION": "Claire Goll filmée au restaurant",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000111",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4178",
            "CLASSIFICATION": "VIIIA110",
            "DESCRIPTION": "Yvan Goll, Buste par Lilly RONA (3 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé"
        },
        {
            "ID": "000112",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4179",
            "CLASSIFICATION": "VIIIA111",
            "DESCRIPTION": "Dessin de Marc CHAGALL (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé.  Dessin original de Marc CHAGALL",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000113",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4180",
            "CLASSIFICATION": "VIIIA112",
            "DESCRIPTION": "Dessin de Marc CHAGALL (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé.  Dessin original de Marc CHAGALL",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000114",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4181",
            "CLASSIFICATION": "VIIIA113 (a et b)",
            "DESCRIPTION": "Illustration de Marc CHAGALL (2 ex. de a)",
            "MATERIALS": "Photos noir et blanc, papier glacé.  Illustration original de Marc CHAGALL",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000115",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4182",
            "CLASSIFICATION": "VIIIA114",
            "DESCRIPTION": "Illustration de Marc CHAGALL pour \"JEAN SANS TERRE\" / 2 ex. de (1)",
            "MATERIALS": "Photos noir et blanc, papier glacé.  Illustration original de Marc CHAGALL",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000116",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4183",
            "CLASSIFICATION": "VIIIA115",
            "DESCRIPTION": "Photo d'une exposition de 4 livres de Claire et Yvan GOLL, ouverts sur des illustrations de Marc CHAGALL",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000117",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4184",
            "CLASSIFICATION": "VIIIA116 1,2,3,4 négatifs",
            "DESCRIPTION": "4 illustrations de Marc CHAGALL pour love poèms de Claire et Yvan Goll",
            "MATERIALS": "Photo noir et blanc, papier glacé. Originaux: dessins",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000118",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4185",
            "CLASSIFICATION": "VIIIA117",
            "DESCRIPTION": "Illustration de Mar CHAGALL (2 ex.)",
            "MATERIALS": "Photo noir et blanc, papier glacé/ Original: dessin",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000119",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4186",
            "CLASSIFICATION": "VIIIA118 (1) et (2)",
            "DESCRIPTION": "Illustration de Marc CHAGALL pour \"Tagebuch eines pferdes\" de Clair Goll",
            "MATERIALS": "Illustrations imprimées",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000120",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4187",
            "CLASSIFICATION": "VIIIA119  négatif",
            "DESCRIPTION": "Illustration de Marc CHAGALL",
            "MATERIALS": "Photo noir et blanc, paier glacé / Original: dessin",
            "AUTHOR": "Original: Marc CHAGALL"
        },
        {
            "ID": "000121",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4188",
            "CLASSIFICATION": "VIIIA120",
            "DESCRIPTION": "Illustration de Fernand LEGER pour \"Poets messages: chansons de France\" d'Yvan GOLL",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: dessin en couleur",
            "AUTHOR": "Original: Fernand LEGER"
        },
        {
            "ID": "000122",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4189",
            "CLASSIFICATION": "VIIIA121",
            "DESCRIPTION": "Photo d'un dessin de Fernand LEGER",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: dessin à l'encre et à la gouache",
            "AUTHOR": "Original: Fernand LEGER"
        },
        {
            "ID": "000123",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4191",
            "CLASSIFICATION": "VIIIA123 (1) (2)2 dessins de André MASSO? \"A Mélusine\" / (1) 2 ex.",
            "DESCRIPTION": "Photos noir et blanc, papier glacé / originaux: dessins",
            "AUTHOR": "Originaux: André MASSON"
        },
        {
            "ID": "000124",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4192",
            "CLASSIFICATION": "VIIIA124 (1) à (3)",
            "DESCRIPTION": "3 Illustrations d'André MASSON pour \"MARA-KIRI\" de Claire Goll",
            "MATERIALS": "Illustrations imprimées / Originaux: dessins",
            "AUTHOR": "Originaux: André MASSON"
        },
        {
            "ID": "000125",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4193",
            "CLASSIFICATION": "VIIIA125 (1) à (4)",
            "DESCRIPTION": "4 ensembles d'Illustrations de Leonor FINI pour \"L'ignifère\" de Claire Goll / (1) 2 ex. (2) 2 ex. (3) 2 ex. (4) 1 ex.",
            "MATERIALS": "Photos noir et blanc, papier glacé / Originaux: dessins",
            "AUTHOR": "Originaux: Leonor FINI"
        },
        {
            "ID": "000126",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4194",
            "CLASSIFICATION": "VIIIA126 (1) à (3) négatifs",
            "DESCRIPTION": "3 illustrations d'Yves TANGUY pour \"Le Mythe de la Roche Percée\" éditions Hémisphères",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: Eau forte",
            "AUTHOR": "Originaux: Yves TANGUY"
        },
        {
            "ID": "000127",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4195",
            "CLASSIFICATION": "VIIIA127 (1) à (3) négatifs",
            "DESCRIPTION": "3 illustrations de Salvador DALI pour \"Les nouvelles petites fleurs de St. François d'Assise\" de Claire et Yvan GOLL / (2) 2 ex. (3) 3 ex.",
            "MATERIALS": "Photos noir et blanc, papier glacé / Originaux: dessins",
            "AUTHOR": "Originaux: Salvador DALI"
        },
        {
            "ID": "000128",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4196",
            "CLASSIFICATION": "VIIIA128 (1) et (2)",
            "DESCRIPTION": "2 Illustrations d'Antoni CLAVE pour \"Petit veau\" de Claire Goll (\"Kälbchen\") 2ex. De chacune",
            "MATERIALS": "Noir et blanc, papier imprimé (Illustrations tramées)",
            "AUTHOR": "Originaux: Antoni CLAVE"
        },
        {
            "ID": "000129",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4197",
            "CLASSIFICATION": "VIIIA129 (1) et (2)",
            "DESCRIPTION": "2 Illustrations de Antoni CLAVE pour \"Taubenwitwe\" de Claire Goll",
            "MATERIALS": "Illustrations extraites d'un livre (tramée)",
            "AUTHOR": "Originaux: Antoni CLAVE"
        },
        {
            "ID": "000130",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4198",
            "CLASSIFICATION": "VIIIA130 négatif",
            "DESCRIPTION": "Illustration de Robert DELAUNAY pour la revue \"Surréalisme\" d'Yvan Goll (La Place de l'Etoile) 2 ex.",
            "MATERIALS": "1 photo noir et blanc, papier glacé / 1 illustration extraite d'un livre (tramée) / originaux: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000131",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4199",
            "CLASSIFICATION": "VIIIA131",
            "DESCRIPTION": "Illustration de Robert DELAUNAY pour \"Paris brûle\" d'Yvan Goll (Tour Eiffel) 4 ex.Photos noir et blanc, papier glacé / Original: dessin",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000132",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4200",
            "CLASSIFICATION": "VIIIA132  négatif",
            "DESCRIPTION": "La Tour Eiffel, dessin de Robert DELAUNAY (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000133",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4201",
            "CLASSIFICATION": "VIIIA133  négatif",
            "DESCRIPTION": "Place de la Concorde, illustration de Robert DELAUNAY",
            "MATERIALS": "Photo noir et blanc, papier glacé/ Original: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000134",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4202",
            "CLASSIFICATION": "VIIIA134 négatif",
            "DESCRIPTION": "Intérieur de l'église St. Séverin par Robert DELAUNAY",
            "MATERIALS": "Photo noir et blanc, papier glacé/ Original: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000135",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4203",
            "CLASSIFICATION": "VIIIA135 négatif",
            "DESCRIPTION": "La Seine, illustration de Robert DELAUNAY",
            "MATERIALS": "Photo noir et blanc, papier glacé/ Original: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000136",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4204",
            "CLASSIFICATION": "VIIIA136 négatif",
            "DESCRIPTION": "Illustration de Robert DELAUNAY pour \"Memoires d'un moineau du siècle\" de Claire Goll (3 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé / Original: dessin",
            "AUTHOR": "Original: Robert DELAUNAY"
        },
        {
            "ID": "000137",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4205",
            "CLASSIFICATION": "VIIIA137 (1) et (2)",
            "DESCRIPTION": "Dessin d'Yvan Goll pour \"Le Mythe de la Roche Percée)",
            "MATERIALS": "Photo noir et blanc, papier glacé/ Original: dessin",
            "AUTHOR": "Original: Yvan GOLL"
        },
        {
            "ID": "000138",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4206",
            "CLASSIFICATION": "VIIA138 négatif",
            "DESCRIPTION": "Dessin de Hans ARP pour \"Die siebente rose\" d'Yvan Goll",
            "MATERIALS": "Photo noir et blanc, papier glacé/ Original: dessin",
            "AUTHOR": "Original: Hans ARP"
        },
        {
            "ID": "000139",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4207",
            "CLASSIFICATION": "VIIIA139 (1) à (3)",
            "DESCRIPTION": "3 compositions de Man Ray: (1) \"T for tie\" / (2) \"Face in the cafe\" / (3) \"Three steps for pets\"",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Originaux: Man RAY"
        },
        {
            "ID": "000140",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4208",
            "CLASSIFICATION": "VIIIA140 (1) et (2)",
            "DESCRIPTION": "2 illustrations de Louradour pour \"Affenlièbe\" (1) et  \"Selbstmord eines hundes\" (2) de Claire Goll",
            "MATERIALS": "2 feuilles imprimés, originaux: dessins",
            "AUTHOR": "Originaux: LOURADOUR"
        },
        {
            "ID": "000141",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4209",
            "CLASSIFICATION": "VIIIA141 négatifs",
            "DESCRIPTION": "Dessin de Wifredo LAM (3 ex.)",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "AUTHOR": "Original: Wifredo LAM"
        },
        {
            "ID": "000142",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4210",
            "CLASSIFICATION": "VIIIA142 négatif",
            "DESCRIPTION": "Dessin de Georges ANNENKOV (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé, original: dessin",
            "AUTHOR": "Original: Georges ANNENKOV"
        },
        {
            "ID": "000143",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4211",
            "CLASSIFICATION": "VIIIA143 (1) et (2) négatifs",
            "DESCRIPTION": "2 dessins de GALANIS: (1) paru dans \"Troisième livre de Jean sans Terre\" d'Yvan Goll",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Original: GALANIS"
        },
        {
            "ID": "000144",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4212",
            "CLASSIFICATION": "VIIIA144 (1) à (4) négatifs",
            "DESCRIPTION": "Illustrations d'Eugène BERMAN (1) Ex.   (2) 1 ex.    (3) 2 ex.",
            "MATERIALS": "Photos noir et blanc, papier glacé, originaux: dessins",
            "AUTHOR": "Originaux: Eugène BERMAN"
        },
        {
            "ID": "000145",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4213",
            "CLASSIFICATION": "VIIA145 négatif",
            "DESCRIPTION": "2 illustrations de Jacques VILLON pour \"Mandalay\" de Claire Goll",
            "MATERIALS": "Photo noir et blanc, papier glacé (les 2 dessins sur la même epreuve) / originaux: dessins",
            "AUTHOR": "Originaux: Jacques VILLON"
        },
        {
            "ID": "000146",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4214",
            "CLASSIFICATION": "VIIIA146 (1) et (2)",
            "DESCRIPTION": "2 illustrations de Kurt SELIGMANN",
            "MATERIALS": "Photos noir et blanc, papier glacé, originaux: dessins",
            "AUTHOR": "Originaux: Kurt SELIGMANN"
        },
        {
            "ID": "000147",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4215",
            "CLASSIFICATION": "VIIIA147 (1) à (8)",
            "DESCRIPTION": "1: Décors et costumes de Medgyes pour \"Mathusalem\" d'Yvan Goll / 2 à 5: Costumes de Medgyes pour cette pièce / 6 et 7: Décors / 8: Personages et décors",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "Originaux: MEDGYES"
        },
        {
            "ID": "000148",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4216",
            "CLASSIFICATION": "VIIIA148",
            "DESCRIPTION": "Sculpture \"La Prière\" de Jacques LIPCHITZ",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: terre cuite (?)",
            "AUTHOR": "Original: Jacques LIPCHITZ"
        },
        {
            "ID": "000149",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4217",
            "CLASSIFICATION": "VIIIA149",
            "DESCRIPTION": "Sculpture \"Else Lasker-Schüler\" par Gina GROSSHUT (3 ex.)",
            "MATERIALS": "Photos noir et blanc (2 ex. papier glacé, 1 ex. papier mat) original: terre cuite",
            "AUTHOR": "Original: Gina GROSSHUT"
        },
        {
            "ID": "000150",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4218",
            "CLASSIFICATION": "VIIA150",
            "DESCRIPTION": "Tableau de PASCIN",
            "MATERIALS": "Photo noir et blanc, papier glacé, original: peinture",
            "AUTHOR": "Original: PASCIN"
        },
        {
            "ID": "000151",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4219",
            "CLASSIFICATION": "VIIIA151 (a et b)",
            "DESCRIPTION": "Portrait de Schiller (2 ex.)",
            "MATERIALS": "a. Carte postale en noir et blanc / b. Feuillet extrait d'un livre, tramé / Original: Peinture",
            "AUTHOR": "Original: Gerhard Von KÜGELGEN"
        },
        {
            "ID": "000152",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4220",
            "CLASSIFICATION": "VIIIA152",
            "DESCRIPTION": "Portrait de Chopin par DELACROIX",
            "MATERIALS": "Photo noir et blanc, papier glacé / Original: Peinture",
            "AUTHOR": "Original: DELACROIX"
        },
        {
            "ID": "000153",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4221",
            "CLASSIFICATION": "VIIIA153 (1) et (2)",
            "DESCRIPTION": "2 illustrations",
            "MATERIALS": "Photos noir et blanc, papier glacé / Originaux: gravures",
            "AUTHOR": "Originaux: XVIème S."
        },
        {
            "ID": "000154",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4222",
            "CLASSIFICATION": "VIIIA154",
            "DESCRIPTION": "Photo: Jean LONGUET",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000155",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4223",
            "CLASSIFICATION": "VIIIA155",
            "DESCRIPTION": "Photo du diner du \"Journal des poètes\" décembre 1958",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000156",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4224",
            "CLASSIFICATION": "VIIIA156",
            "DESCRIPTION": "Claire GOLL avec E. LE BIHAN",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "17,7X24 cm"
        },
        {
            "ID": "000157",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4225",
            "CLASSIFICATION": "VIIIA157 (1) et (2)",
            "DESCRIPTION": "2 photos de Paul ELUARD",
            "MATERIALS": "Photos noir et blanc",
            "DIMENSIONS": "1: 23X18 cm / 2: 22X18 cm"
        },
        {
            "ID": "000158",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4226",
            "CLASSIFICATION": "VIIIA158",
            "DESCRIPTION": "Photo d'un chef d'orchestre (Ferdinand LEIBNER)",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "17X23,3 cm",
            "AUTHOR": "Dr. Theo GRASSER"
        },
        {
            "ID": "000159",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4227",
            "CLASSIFICATION": "VIIIA159",
            "DESCRIPTION": "Fritz Von UNRUH devant le portrait qu'il fit de Claire et Yvan Goll (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "DIMENSIONS": "8,3X11,6 cm"
        },
        {
            "ID": "000160",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4228",
            "CLASSIFICATION": "VIIIA160",
            "DESCRIPTION": "Photo de Darius MILHAUD",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "17,4C13,1 cm"
        },
        {
            "ID": "000161",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4229",
            "CLASSIFICATION": "VIIIA161",
            "DESCRIPTION": "Mme Yvonne MALET",
            "MATERIALS": "Photo noir et blanc, papier mat"
        },
        {
            "ID": "000162",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4230",
            "CLASSIFICATION": "VIIIA162",
            "DESCRIPTION": "Photo de Marcel MIHALOVICI",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "14,6X10,3 cm",
            "AUTHOR": "Studio SEPP JÄGER, Francfort"
        },
        {
            "ID": "000163",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4231",
            "CLASSIFICATION": "VIIIA163",
            "DESCRIPTION": "Photo de Gian-Carlo MENOTTI",
            "MATERIALS": "Photo noir et blanc, papier mat",
            "DIMENSIONS": "25,3X20,2 cm"
        },
        {
            "ID": "000164",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4232",
            "CLASSIFICATION": "VIIIA164",
            "DESCRIPTION": "Photo de Paco RABANNE",
            "MATERIALS": "Photo noir et blanc, papier glacé",
            "DIMENSIONS": "23,9X17,8 cm"
        },
        {
            "ID": "000165",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4233",
            "CLASSIFICATION": "VIIIA165 (1) à (3)",
            "DESCRIPTION": "1: Brigitte BARDOT / 2: Mylène DEMONGEOT (2 ex.)",
            "MATERIALS": "Photos noir et blanc, papier glacé",
            "AUTHOR": "2 et 3: Jean Pierre FIZET"
        },
        {
            "ID": "000166",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4234",
            "CLASSIFICATION": "VIIIA166 (1) et (2)",
            "DESCRIPTION": "Georges KAISER",
            "MATERIALS": "Photos noir et blanc / 1: avec dos de carte postale pohotographié / 2: tramé"
        },
        {
            "ID": "000167",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4235",
            "CLASSIFICATION": "VIIIA167",
            "DESCRIPTION": "ZAO WOU-KI",
            "MATERIALS": "Photo noir et blanc, tramée (carton d'invitation à un vernissage)",
            "DIMENSIONS": "15,6X24 cm"
        },
        {
            "ID": "000168",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4236",
            "CLASSIFICATION": "VIIIA168",
            "DESCRIPTION": "Paul Valéry, dessin de Marie-Elisabeth WREDE",
            "MATERIALS": "Photo noir et blanc, papier mat"
        },
        {
            "ID": "000169",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4237",
            "CLASSIFICATION": "VIIIA169",
            "DESCRIPTION": "Scène d'extèrieur vers 1925",
            "MATERIALS": "Photo noir et blanc, papier glacé"
        },
        {
            "ID": "000170",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4238",
            "CLASSIFICATION": "VIIIA170",
            "DESCRIPTION": "Leonor FINI",
            "MATERIALS": "Photo noir et blanc",
            "DIMENSIONS": "0,376X,0257 m",
            "AUTHOR": "Atelier Karl-Heinz BAST, Bonn (RFA)"
        },
        {
            "ID": "000171",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4239",
            "CLASSIFICATION": "VIIIA171  négatifs",
            "DESCRIPTION": "Illustrations de Fernand LEGER pour \"les cercles magiques\"",
            "MATERIALS": "Photos noir et blanc, glacé (repros film trait)"
        },
        {
            "ID": "000172",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4240",
            "CLASSIFICATION": "VIIIA172 négatifs",
            "DESCRIPTION": "Illustrations (bois gravés) de Jean ARP pour \"Multiple Femme\" / 1: Page de titre / 2 à 9: Tirages signés, repros",
            "MATERIALS": "Photos noir et blanc (repros film trait)"
        },
        {
            "ID": "000173",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4241",
            "CLASSIFICATION": "VIIIA173 (1) (2)  négatifs",
            "DESCRIPTION": "Illustrations de CHAGALL pour \"L'Antirose\"",
            "MATERIALS": "Photos noir et blanc, glacé  (3) contact-repro"
        },
        {
            "ID": "000174",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4242",
            "CLASSIFICATION": "VIIIA174  négatif",
            "DESCRIPTION": "Illustration de CHAGALL pour \"Journal d'un cheval\"",
            "MATERIALS": "Photo noir et blanc, glacé / contact-repro"
        },
        {
            "ID": "000175",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4243",
            "CLASSIFICATION": "VIIIA175  négatifs  1,2,3,4,5,6,7,8",
            "DESCRIPTION": "Illustrations de MATISSE pour \"Chansons Malaises",
            "MATERIALS": "Photos noir et blanc, glacé   contacts-repros"
        },
        {
            "ID": "000176",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4244",
            "CLASSIFICATION": "VIIIA176   négatif",
            "DESCRIPTION": "Reproduction photo d'une empreinte de la main de Claire Goll",
            "MATERIALS": "Photo noir et blanc, glacé",
            "DIMENSIONS": "18X24 cm"
        },
        {
            "ID": "000177",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4245",
            "CLASSIFICATION": "VIIIA177  négatif",
            "DESCRIPTION": "Masque mortuaire d'Yvan Goll",
            "MATERIALS": "Photo noir et blanc, glacé",
            "DIMENSIONS": "13X18 cm"
        },
        {
            "ID": "000178",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4246",
            "CLASSIFICATION": "VIIIA178",
            "DESCRIPTION": "Article de journal allemand, James Joyce et Sylvia Beach, son éditrice",
            "MATERIALS": "Photo noir et blanc, glacé",
            "DIMENSIONS": "10X12,5 cm"
        },
        {
            "ID": "000179",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4247",
            "CLASSIFICATION": "VIIIA179",
            "DESCRIPTION": "Albert EINSTEIN",
            "MATERIALS": "Photographie sépia",
            "DIMENSIONS": "Cadre: 0,405X0,30 m / Photo: 0,27X0,175 m avec inscription"
        },
        {
            "ID": "000180",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "4972",
            "CLASSIFICATION": "VIIIA180",
            "DESCRIPTION": "Photographie des œuvres Lilith et Sollune",
            "MATERIALS": "Photographie en noir et blanc",
            "DIMENSIONS": "0,127X0,072 m"
        },
        {
            "ID": "000181",
            "LOCATION": "MUSEE PIERRE NOEL",
            "MEDIA": "P",
            "INVENTORY": "2003-25-2",
            "CLASSIFICATION": "VIIIA181",
            "DESCRIPTION": "Leonardo Da Vinci et la Gioconde",
            "MATERIALS": "Photographie originale",
            "DIMENSIONS": "Fenetre: 0,345X0,280 m / Cadre: 0,47X0,43 m",
            "AUTHOR": "Tableau: Valentine HUGO"
        }
    ];